### PR TITLE
Update again the vocabulary json file with QO MLI inputs

### PR DESCRIPTION
**Pull request by JessyBarrette**

### CODE REVIEW

**Comment by n-a-t-e** [comment]
looks like you have some extra file changes in here you probably didn't mean to add, eg deleting odf_to_json.py

**Review by pramod-thupaki — CHANGES_REQUESTED** [review]
@JessyBarrette could you please address this comment before the merge ? (https://github.com/cioos-siooc/cioos-siooc_data_transform/pull/60#issuecomment-782394480)

**Comment by JessyBarrette** [comment]
Oh yeah sorry I'll change that

**Comment by JessyBarrette** [comment]
@n-a-t-e there it is should be good now! Nice catch!

**Review by pramod-thupaki — APPROVED** [review]

**Pull request merged**
